version: '3.2'

services:
  php:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /var/www/
    container_name: php
    ports:
      - 9000:9000
    volumes:
     - ./:/var/www/
     - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php_conf.ini
  
   #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/

      
  mysql:
        image: 'mysql:8.0.30'
        ports:
            - '3306:3306'
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - './.docker/mysql:/var/lib/mysql'
      


